import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import "./globals.css";
import { CartProvider } from "@/context/CartContext";

export const metadata = {
  title: "Tou De Sweet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body className="relative">
        <div className="mb-[18rem]"></div>
        <CartProvider>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
